config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, except: [:index, :show]
  resources :dilemmas, except: [:edit, :destroy] do
    resources :options, only: [:new, :create]
    resources :replies, only: [:new, :create]
  end
  resources :replies, only: :destroy
  get '/options/:id/upvotes', to: 'options#upvotes', as: :upvotes
  get '/replies/:id/mark', to: 'replies#mark', as: :mark
  get '/users/profile', to: 'users#profile', as: :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dilemma.rb
class Dilemma < ApplicationRecord
  belongs_to :user
  has_many :options, dependent: :destroy
  has_many :replies, dependent: :destroy
  validates :question, presence: true
  validates :category, presence: true
  validates :question, length: {
    maximum: 140
  }
  enum category: [ :easy, :medium, :hard ]
  has_one_attached :photo

  accepts_nested_attributes_for :options, allow_destroy: true

  after_create :assign_expiration

  scope :expired, -> { where("expired_at < ?", Time.zone.now) }

  scope :active, ->  { where("expired_at > ?", Time.zone.now) }

  def can_users_vote?
    self.expired_at > Time.zone.now
  end

  def remaining_time
    self.expired_at - created_at
  end

  def has_user_voted?(user)
    voted = false
    self.options.each do |option|
      if user.options.where("options_users.option_id = ?", option.id).any?
        voted = true
      end
    end
    voted
  end

  def user_voted_reply?(user)
    voted = false
    self.replies.each do |reply|
      if user.replies.where("replies_users.reply_id = ?", reply.id).any?
        voted = true
      end
    end
    voted
  end

  def self.top_3
    @dilemmas = Dilemma.all.active.sort_by { |dilemma| dilemma.replies.count }
    @dilemmas.first(3)
  end

  def self.sample
    @dilemma = Dilemma.all.sample
  end

  private

  def assign_expiration
    if self.category == "easy"
      self.expired_at = self.created_at + 1.day
    elsif self.category == "medium"
      self.expired_at = self.created_at + 3.day
    elsif self.category == "hard"
      self.expired_at = self.created_at + 1.week
    end
    self.save
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :dilemma
  has_and_belongs_to_many :users
  validates :description, presence: true
  validates :description, length: {
    maximum: 140
  }
  has_one_attached :photo
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :dilemma
  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  has_and_belongs_to_many :users
  validates :answer, length: {
    minimum: 1, maximum: 280
  }

  def created_by?(user)
    owner == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dilemmas, dependent: :destroy
  has_many :replies, foreign_key: :owner_id
  has_and_belongs_to_many :options
  has_and_belongs_to_many :replies
  validates :username, presence: true, uniqueness: true, length: {
    maximum: 12
  }
  has_one_attached :avatar
  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.send("welcome_email", self).deliver_now
  end

  def self.show_dilemma
    @users = User.all
    @user = user.dilemma.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :answered_dilemmas, :avatar, :bio])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :answered_dilemmas, :avatar, :bio])
  end

  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end

#  def after_sign_out_path_for(_resource_or_scope)
#    root_path
#  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dilemmas_controller.rb
class DilemmasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_dilemma, only: [:show, :edit, :update, :destroy]

  def index
    @dilemmas = policy_scope(Dilemma)
    if params[:query].present?
      sql_query = "question ILIKE :query OR tag ILIKE :query"
      @dilemmas = Dilemma.where(sql_query, query: "%#{params[:query]}%")
    else
      @dilemmas = Dilemma.all
    end
  end

  def show
    @dilemmas = Dilemma.all
    @reply = Reply.new
  end

  def new
    @dilemma = Dilemma.new
    @dilemma.options.build
    authorize @dilemma
  end

  def create
    @dilemma          = Dilemma.new(dilemma_params)
    @dilemma.category = params["dilemma"]["category"].to_i
    @dilemma.user_id  = current_user.id

    authorize @dilemma

    if @dilemma.save!
      redirect_to dilemma_path(@dilemma)
    else
      render :new
    end
  end

  private

  def find_dilemma
    @dilemma = Dilemma.find(params[:id])
    authorize @dilemma
  end

  def dilemma_params
    params.require(:dilemma).permit(:question, :context, :expired_at, :photo, {options_attributes: [:description]})
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  def new
    @dilemma = Dilemma.find(params[:dilemma_id])
    @option = Option.new
  end

  def create
    @dilemma = Dilemma.find(params[:dilemma_id])
    @option = Option.new(option_params)
    @option.dilemma = @dilemma

    @option.save
  end

  def upvotes
    @option = Option.find(params[:id])
    @option.users.push(current_user)
    authorize @option

    @option.save!
    redirect_to dilemma_path(@option.dilemma)
  end

  private

  def option_params
    params.require(:option).permit(:description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def new
    @dilemma = Dilemma.find(params[:dilemma_id])
    @reply = Reply.new
    authorize @reply
  end

  def create
    @dilemma = Dilemma.find(params[:dilemma_id])
    @reply = Reply.new(reply_params)
    @reply.dilemma_id = params[:dilemma_id]
    @reply.user_id = current_user.id
    @reply.owner_id = current_user.id
    authorize @reply
    if @reply.save
      DilemmaChannel.broadcast_to(
      @dilemma,
      render_to_string(partial: "display-replies", locals: { reply: @reply })
      )
      respond_to do |format|
        format.html {redirect_to dilemma_path(@dilemma)}
        format.js {redirect_to dilemma_path(@dilemma)}
      end

    else
      render "dilemmas/show"
    end
  end

  def destroy
    @reply.destroy

    redirect_to dilemma_path(@dilemma)
  end

  def mark
    @reply = Reply.find(params[:id])
    @reply.users.push(current_user)
    authorize @reply

    @reply.save!
    redirect_to dilemma_path(@reply.dilemma)
  end

  private

  def reply_params
    params.require(:reply).permit(:answer, :reply_votes)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    skip_authorization
    @user = current_user
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/dilemmas/_display-featured.html.erb
     <% @dilemmas.each do |dilemma| %>
          <% if dilemma.easy? %>
            <div class="m-2">
              <div class="easy card-category-easy card-note-text">
                <%= link_to "#{dilemma.question}", dilemma_path(dilemma) %>
                <p class="font-italic">Created by <%= dilemma.user.username %></p>
              </div>
            </div>
          <% end %>
        <% end %>

app/views/dilemmas/_display-show.html.erb
<div class="card-box-show container mt-4 p-5 <%= dilemma.category %>">
  <div class="border border-dark">
    <div class="p-5">
      <% if dilemma.category? %>
        <p class="ml-5 px-2 py-1 d-inline little-text-border">
          <%= render "distance_in_time", dilemma: dilemma %>
        </p>
      <% end %>
      <h2 class="p-3 pb-3 border-bottom border-dark"><%= dilemma.question %></h2>
      <p class="pl-5"><strong><%= dilemma.user.username %>'s</strong> dilemma</p>
    </div>
    <div class="context-box">
      <p class="border-left border-white pl-3"><%= dilemma.context %></p>
    </div>
    <div class="container d-flex flex-column justify-content-center">
      <div class="d-flex justify-content-around">
        <% dilemma.options.each do |option| %>
            <% if dilemma.has_user_voted?(current_user) || dilemma.user == current_user || !dilemma.can_users_vote? %>
              <div class="show-options d-flex flex-column align-items-center mx-5 mb-5 p-3">
                <div class="circle-percentage mb-1">
                  <% percentage = dilemma.options.reduce(0) { |sum, option| sum + option.users.count } %>
                  <% if percentage > 0 %>
                    <%= (option.users.count * 100) / percentage  %> %
                  <% else %>
                    0%
                  <% end %>
                </div>
                <p class="text-dark"><%= option.description %></p>
              </div>
            <% else %>
              <%= link_to upvotes_path(option.id) do %>
                <div class="show-options d-flex flex-column align-items-center mx-5 mb-5 p-4 card-ghost card-grow">
                  <p class="badge badge-primary"><strong>Vote!</strong></p>
                  <div class="circle-percentage mb-1">
                    <% percentage = dilemma.options.reduce(0) { |sum, option| sum + option.users.count } %>
                    <% if percentage > 0 %>
                      <%= (option.users.count * 100) / percentage  %> %
                    <% else %>
                      0%
                    <% end %>
                  </div>
                  <p class="text-dark text-bold" id="text-vote-option"><%= option.description %></p>
                </div>
              <% end %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dilemmas/_distance_in_time.html.erb
<% if dilemma.can_users_vote? %>
  <%= "#{time_ago_in_words(dilemma.expired_at)} left" %>
<% else %>
  <%= "Expired #{time_ago_in_words(dilemma.expired_at)} ago" %>
<% end %>

app/views/dilemmas/index.html.erb
<div class="container-fluid">
  <% if @dilemmas.empty? %>
    <div class="mb-2 ml-3">
      <div class="form-inline">
        <%= form_tag dilemmas_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Want to search again?"%>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="text-center mt-5">
      <%= link_to ">> No dilemmas found 🤖. I think you should create one <<", new_dilemma_path %>
    </div>
  <% else %>
    <div class="mb-2 ml-3">
      <div class="form-inline">
        <%= form_tag dilemmas_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "What's on your mind?"%>
          <%= submit_tag "Search", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <!-- Dilemmas -->
    <div class="container-fluid">
      <!-- active dilemmas -->
      <div class="row">
        <% @dilemmas.active.each do |dilemma| %>
          <div class="col-3">
            <div class="mt-3 mb-5 color-parent card-ghost card-category card-note-text">
              <div class="color-child rounded-circle <%= dilemma.category %>"></div>
                <% if dilemma.can_users_vote? %>
                  <% if dilemma.easy? %>
                    <p class="px-2 py-1 d-inline little-text-border">ACTIVE FOR 1 DAY</p><br>
                  <% elsif dilemma.medium? %>
                    <p class="px-2 py-1 d-inline little-text-border mt-0">ACTIVE FOR 3 DAYS</p><br>
                  <% elsif dilemma.hard? %>
                    <p class="px-2 py-1 d-inline little-text-border">ACTIVE FOR 7 DAYS</p><br>
                  <% end %>
                <% end %>
              <div class="mt-1" id="min-card-width"><%= link_to "#{dilemma.question}", dilemma_path(dilemma) %></div>
              <p class="font-italic little-text">Created by <strong><%= dilemma.user.username %></strong></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="container-fluid">
      <!-- expired dilemmas -->
      <div class="row">
        <% @dilemmas.expired.each do |dilemma| %>
          <div class="col-3">
            <div class="mt-3 mb-5 color-parent card-ghost card-category card-note-text">
              <div class="color-child rounded-circle <%= dilemma.category %>"></div>
              <p class="px-2 py-1 d-inline little-text-border">EXPIRED</p>
              <div class="mt-1" id="min-card-width"><%= link_to "#{dilemma.question}", dilemma_path(dilemma) %></div>
              <p class="font-italic little-text">Created by <strong><%= dilemma.user.username %></strong></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/dilemmas/show.html.erb
<div class="container-show m-0">
  <div class="row">
    <div class="col-lg-8">
      <!-- Dilemma card -->
      <%= render "display-show", dilemma: @dilemma %>
      <!-- Social Media Buttons -->
      <br>
      <div class="share-btn" data-url="http://decide-for.me" data-title="Dilemma" data-desc="Share a dilemma with your friends">
        <a class="btn-facebook" data-id="fb"><i class="fab fa-facebook-square"></i> Facebook</a>
        <a class="btn-twitter" data-id="tw"><i class="fab fa-twitter"></i> Twitter</a>
        <a class="btn-telegram" data-id="tg"><i class="fab fa-telegram"></i> Telegram</a>
        <a class="btn-mail" data-id="mail"><i class="fas fa-at"></i> EMail</a>
      </div>
      <!-- Comments section -->
      <div class="mt-5" id="replies" data-chatroom-id="<%= @dilemma.id%>">
        <% @dilemma.replies.each do |reply| %>
          <%= render "replies/display-replies", reply: reply, dilemma: @dilemma %>
        <% end %>
      </div>
    </div>
    <!-- Form for comments -->
    <%= render "display-reply", dilemma: @dilemma %>
  </div>
</div>

app/views/pages/home.html.erb
<!-- First section -->
<div class="background-pattern" style="background-image: url('https://res.cloudinary.com/dusgqtd1w/image/upload/v1593623380/doodle.png');">
  <div class="background-transparency text-center p-4">
    <h1 class="border-bottom"><%= link_to "DECIDE FOR ME", dilemmas_path %></h1>
    <h5>collective decision-making</h5>
    <div class="d-flex form-inline justify-content-center">
      <%= form_tag dilemmas_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "What's on your mind?"%>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<!-- Second section -->
<div class="background-dark">
  <div class="d-flex">
    <div class="color-card-half bg-primary mx-2 my-2 p-2">
      <h2>Should I get a new job?</h2>
      <div class="d-flex">
        <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
        <p class="font-italic little-text">Created by <strong>Iben</strong></p>
      </div>
    </div>
    <div class="color-card bg-light mx-1 my-2">
      <%= image_tag "https://images.unsplash.com/photo-1548543604-a87c9909abec?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=634&q=80" %>
    </div>
    <div class="color-card bg-info mx-1 my-2 p-3">
      <h2>Should I get married?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>Joselito</strong></p>
    </div>
    <div class="color-card bg-light mx-1 my-2">
      <%= image_tag "https://images.unsplash.com/photo-1518800431428-69a992a6f54a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" %>
    </div>
    <div class="color-card bg-success mx-1 my-2 p-3">
      <h2>Beach or pool this weekend?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>JolieFolie</strong></p>
    </div>
    <div class="color-card-half bg-warning mx-1 my-2 p-2">
      <h2>Rent or buy my next place?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>JolieFolie</strong></p>
    </div>
  </div>
  <div class="d-flex">
    <div class="color-card bg-warning mx-1 p-3">
      <h2>Brunette or blond?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>Faith</strong></p>
    </div>
    <div class="color-card bg-light mx-1">
      <%= image_tag "https://images.unsplash.com/photo-1522776507896-7174e7b0219d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80" %>
    </div>
    <div class="color-card bg-primary mx-1 p-3">
      <h2>Should I forbid cellphones in my class?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>Raj</strong></p>
    </div>
    <div class="color-card bg-info mx-1 p-3">
      <h2>Who would you rather meet?</h2>
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <p class="font-italic little-text">Created by <strong>MarianaGT</strong></p>
    </div>
    <div class="color-card bg-success mx-1">
      <%= image_tag "https://images.unsplash.com/photo-1505243542579-da5adfe8338f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" %>
    </div>
  </div>
</div>
<!-- Third section -->
<div class="white-container p-4 mt-2">
  <div class="bg-white d-flex justify-content-center align-items-center py-5 my-2">
    <div class="white-container-text p-5 text-left">
      <p>You have a problem?</p>
      <p>Not sure what to do?</p>
      <br>
      <p class="bg-info">You post it!</p>
    </div>
    <div class="mt-3 mb-5 color-parent card-ghost card-category card-note-text">
      <p class="px-1 d-inline little-text-border">ACTIVE FOR 1 DAY</p>
      <h3>Where should I travel to next?</h3>
      <p class="font-italic little-text">Created by <strong>Memo</strong></p>
    </div>
  </div>
</div>
<!-- Fourth section -->
<div class="space-container">
</div>
<div class="quote-section">
    <div class="px-2 py-5">
      <h3 class="text-white">Receive <strong>feedback</strong> on any dilemma<br>
      <span>you're <em>indecisive</em> about</span></h3>
    </div>
</div>
<!-- Fifth section -->
<div class="white-container pt-4 pb-3">
  <div class="bg-white d-flex justify-content-center align-items-center py-5 my-2">
    <div class="mt-3 mb-5 color-parent card-ghost card-category card-note-text" id="card-fourth-section">
      <h3>How does this app work?</h3>
      <p class="font-italic little-text">Created by <strong>The Team</strong></p><br>
      <div class="d-flex align-items-center">
        <p class="px-1 d-inline little-text-border mt-3">ACTIVE FOR 1 DAY</p>
        <div class="circle rounded-circle easy ml-3"></div>
        <p class="little-text text-white ml-1">EASY</p>
      </div>
      <div class="d-flex align-items-center">
        <p class="px-1 d-inline little-text-border mt-3">ACTIVE FOR 3 DAYS</p>
        <div class="circle rounded-circle medium ml-2"></div>
        <p class="little-text text-white ml-1">MEDIUM</p>
      </div>
      <div class="d-flex align-items-center">
        <p class="px-1 d-inline little-text-border mt-3">ACTIVE FOR 7 DAYS</p>
        <div class="circle rounded-circle hard ml-2"></div>
        <p class="little-text text-white ml-1">HARD</p>
      </div>
      <br>
      <p><span class="px-1 d-inline little-text-border mt-3">ACTIVE</span>
        or<span class="px-1 d-inline little-text-border mt-3 ml-2">EXPIRED</span></p>
    </div>
    <div class="white-container-text text-right ml-2 mb-5">
      <div class="mb-5 pb-5 ml-5">
        <p class="text-center">Navigate</p><br>
        <div class="d-flex align-items-center justify-content-center">
          <div class="btn btn-primary mr-3">Search</div><br>
          <div class="btn btn-outline-primary little-text mr-4" id="btn-thin">
            <i class="fas fa-circle-notch pr-1"></i>
            <a>Post a dilemma</a>
          </div><br>
        </div>
        <div class="d-flex align-items-center justify-content-center mt-2 mb-1">
          <div class="text-white pt-1">
            <p class="badge badge-primary mr-2"><strong>Vote!</strong></p>
            <i class="fas fa-comments text-secondary"></i>
            <p class="badge badge-secondary text-wrap p-1"><strong>ADD A COMMENT</strong></p>
          </div>
        </div>
      </div>
      <p class="bg-info pl-3">Categorize by complexity</p>
    </div>
  </div>
</div>
<div class="space-container">
</div>
<!-- Sixth section -->
<div class="space-container p-5">
</div>
<div class="quote-section-last">
  <div class="mx-5 mt-5 d-flex justify-content-center">
    <i class="fas fa-quote-left text-white pr-1"></i>
    <h4 class="text-white"><em>No dilemma is</em> too small or big <em>when we gather
    <br>as a <strong>community</strong> to help each other decide.</em></h4><br>
    <i class="fas fa-quote-right text-white pl-2"></i>
  </div>
</div>

app/views/replies/_display-replies.html.erb
<div class="reply-container mb-3">
  <div class="d-flex justify-content-between align-items-center pr-3 pt-2 pb-1 mx-2">
    <div class="badge badge-dark text-wrap"><strong><%= reply.owner.username %></strong></div>
    <% if reply.owner.avatar.attached? %>
      <div class="pr-3 pl-2"><%= cl_image_tag reply.owner.avatar.key, class: "avatar-bordered" %></div>
    <% else %>
      <div class="pr-3 pl-2"><%= image_tag "default_avatar.png", class: "avatar-bordered" %></div>
    <% end %>
    <div class="flex-grow-1 pl-3 text-black border-left border-dark rounded mb-1" id="bg-comment">
      <i class="fas fa-comment pl-3 pr-2 text-dark"></i>
      <%= reply.answer %>
      <% if  reply.users.count > 50 %>
        <%= cl_image_tag('50_points.png', :class => "avatar-bordered") %>
      <% elsif reply.users.count > 40 %>
        <%= cl_image_tag('40_points.png', :class => "avatar-bordered") %>
      <% elsif reply.users.count > 30 %>
        <%= cl_image_tag('30_points.png', :class => "avatar-bordered") %>
      <% elsif reply.users.count > 20 %>
        <%= cl_image_tag('20_points.png', :class => "avatar-bordered") %>
      <% elsif reply.users.count > 10 %>
        <%= cl_image_tag('10_points.png', :class => "avatar-bordered") %>
      <% end %>
      <!-- click on the icon, sum +1 to reply_votes -->
      <% if reply.created_by?(current_user) || dilemma.user_voted_reply?(current_user) %>
        <span class="px-3">
          <i class="fas fa-star text-primary"></i>
          <span class="little-text text-primary"><%= reply.users.count %></span>
        </span>
      <% else %>
        <%= link_to mark_path(reply.id) do %>
          <span class="px-3">
            <i class="fas fa-star icon-reply"></i>
            <span class="little-text text-primary text-right"><%= reply.users.count %></span>
          </span>
        <% end %>
      <% end %>
      <br><p class="text-black border-top border-dark mt-1 mr-2" style="font-size: 10px;"><%= "Posted #{time_ago_in_words(reply.created_at)} ago" %></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-space-between mx-5">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-comments"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <div class="btn btn-outline-primary pr-2 mt-2 little-text" id="btn-thin">
            <i class="fas fa-circle-notch pr-1"></i>
            <%= link_to "All dilemmas", dilemmas_path %>
          </div>
        </li>
        <li class="nav-item">
          <div class="btn btn-outline-primary mx-5 mt-2 little-text" id="btn-thin">
            <i class="fas fa-circle-notch pr-1"></i>
            <%= link_to "Post a dilemma", new_dilemma_path %>
          </div>
        </li>
        <li class="nav-item active mr-2 ml-5 mt-2 mb-3">
          <%= current_user.username %>
        </li>
        <li class="nav-item dropdown">
          <%  if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "default_avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Browse dilemmas", dilemmas_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active pr-2 pl-5 pt-1 little-text" id="text-blue">
          <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active pr-2 pl-5 pt-1 little-text" id="text-blue">
          <%= link_to "SIGN UP", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>